package tqs.lab4_2;

// Generated by Selenium IDE  
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import org.junit.jupiter.api.extension.ExtendWith;
import io.github.bonigarcia.seljup.SeleniumJupiter;



import static java.lang.invoke.MethodHandles.lookup;
import static org.assertj.core.api.Assertions.assertThat;
import static org.slf4j.LoggerFactory.getLogger;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.slf4j.Logger;

import io.github.bonigarcia.wdm.WebDriverManager;

@ExtendWith(SeleniumJupiter.class)
class BlazeTest {


    static final Logger log = getLogger(lookup().lookupClass());

    private WebDriver driver;

    @BeforeAll
    static void setupClass() {
        WebDriverManager.chromedriver().clearDriverCache().setup();
    }

    @BeforeEach
    void setup() {
        driver = new ChromeDriver();
    }

    @Test
    void test() {
        // Exercise
        String sutUrl = "https://bonigarcia.dev/selenium-webdriver-java/";
        driver.get(sutUrl);
        String title = driver.getTitle();
        log.debug("The title of {} is {}", sutUrl, title);

        // Verify
        assertThat(title).isEqualTo("Hands-On Selenium WebDriver with Java");
    }

    @AfterEach
    void teardown() {
        driver.quit();
    }

    @Test
    public void blaze() {
      driver.get("https://blazedemo.com/index.php");
      driver.manage().window().setSize(new Dimension(1845, 1053));
      {
        WebElement dropdown = driver.findElement(By.name("fromPort"));
        dropdown.findElement(By.xpath("//option[. = 'Portland']")).click();
      }
      {
        WebElement element = driver.findElement(By.name("fromPort"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).clickAndHold().perform();
      }
      {
        WebElement element = driver.findElement(By.name("fromPort"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
      }
      {
        WebElement element = driver.findElement(By.name("fromPort"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).release().perform();
      }
      {
        WebElement dropdown = driver.findElement(By.name("fromPort"));
        dropdown.findElement(By.xpath("//option[. = 'Mexico City']")).click();
      }
      {
        WebElement element = driver.findElement(By.name("fromPort"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).clickAndHold().perform();
      }
      {
        WebElement element = driver.findElement(By.name("fromPort"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
      }
      {
        WebElement element = driver.findElement(By.name("fromPort"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).release().perform();
      }
      {
        WebElement dropdown = driver.findElement(By.name("toPort"));
        dropdown.findElement(By.xpath("//option[. = 'New York']")).click();
      }
      {
        WebElement element = driver.findElement(By.name("toPort"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).clickAndHold().perform();
      }
      {
        WebElement element = driver.findElement(By.name("toPort"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
      }
      {
        WebElement element = driver.findElement(By.name("toPort"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).release().perform();
      }
      driver.findElement(By.cssSelector(".btn-primary")).click();
      driver.findElement(By.cssSelector("tr:nth-child(1) .btn")).click();
      driver.findElement(By.id("inputName")).click();
      driver.findElement(By.id("inputName")).sendKeys("adsdsadasdsa");
      driver.findElement(By.cssSelector(".control-group:nth-child(3) > .controls")).click();
      driver.findElement(By.id("address")).click();
      driver.findElement(By.id("address")).sendKeys("asdsadsdsda");
      driver.findElement(By.id("city")).click();
      driver.findElement(By.id("city")).sendKeys("asdasdasdasd");
      driver.findElement(By.id("state")).click();
      driver.findElement(By.id("state")).sendKeys("asdasdsads");
      driver.findElement(By.id("zipCode")).click();
      driver.findElement(By.id("zipCode")).sendKeys("2131231");
      {
        WebElement dropdown = driver.findElement(By.id("cardType"));
        dropdown.findElement(By.xpath("//option[. = \"Diner's Club\"]")).click();
      }
      {
        WebElement element = driver.findElement(By.id("cardType"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).clickAndHold().perform();
      }
      {
        WebElement element = driver.findElement(By.id("cardType"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
      }
      {
        WebElement element = driver.findElement(By.id("cardType"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).release().perform();
      }
      driver.findElement(By.id("creditCardNumber")).click();
      driver.findElement(By.id("creditCardNumber")).sendKeys("asddadsadd");
      driver.findElement(By.id("creditCardMonth")).click();
      driver.findElement(By.id("creditCardMonth")).sendKeys("11aa");
      driver.findElement(By.id("creditCardYear")).click();
      driver.findElement(By.id("nameOnCard")).click();
      driver.findElement(By.id("nameOnCard")).sendKeys("adasdasds");
      driver.findElement(By.cssSelector(".checkbox")).click();
      driver.findElement(By.cssSelector(".btn-primary")).click();
      driver.findElement(By.linkText("Travel The World")).click();
      driver.findElement(By.linkText("destination of the week! The Beach!")).click();
      driver.findElement(By.cssSelector(".img-rounded")).click();
    }
}
